# Generated by Django 5.0.6 on 2024-05-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='комментарий'),
        ),
    ]
