# Generated by Django 5.0.6 on 2024-05-21 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mailing_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='признак блокировки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='stop_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата и время окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 20, 4, 47, 957839), verbose_name='Дата и время старта рассылки'),
        ),
    ]
