# Generated by Django 5.0.6 on 2024-05-21 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mailing_is_active_mailing_stop_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 22, 38, 2, 871543), verbose_name='Дата и время старта рассылки'),
        ),
    ]
