# Generated by Django 5.0.6 on 2024-05-22 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_mailing_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('id',), 'permissions': [('set_is_active_status', "Can set 'is_active' status")], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 20, 37, 55, 225681), verbose_name='Дата и время старта рассылки'),
        ),
    ]
