# Generated by Django 5.0.6 on 2024-05-24 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_mailing_options_alter_mailing_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 22, 38, 53, 295754), verbose_name='Дата и время следующего старта рассылки'),
        ),
    ]
